services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ab_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql-db
    volumes:
      - ./create_superuser.py:/app/create_superuser.py
    command: >
      sh -c "wait-for-it mysql-db:3306 -- && \
      cd /app/addressBook/myproject && \
      python manage.py makemigrations && \
      echo 'Running migrations...' && python manage.py migrate && \
      echo 'Creating superuser...' && python manage.py shell < /app/create_superuser.py && \
      echo 'Starting server...' && python manage.py runserver 0.0.0.0:80"
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent communication
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

volumes:
  mysql_data:
  jenkins_data:
